### ISSUE TITLE
[BUG] Applying TEMP HP also removes current "normal" HP

### ISSUE THREAD

**Issue by Juno-N** [Larkinabout/fvtt-custom-dnd5e#146]
**Describe the bug**

Hi there! This is whats happening:
When an ability is used to give a target temporary HPs, like the INSPIRING LEADER ability, at the right moment to APPLY the "damage" rolled, or in this particular case, calculated, the target's normal HP is completely erased.  The TEMP HP is applied as expected, tho.
Could you guys look into it?

![Apply Temp HP](https://github.com/user-attachments/assets/fc282b55-89d5-42d4-a573-8e2694a0c27e)

Console Error MSG
![console error](https://github.com/user-attachments/assets/6f45fc8e-4aac-4f27-80a8-d953eb306507)

THANKS

**Module Data**
[custom-dnd5e error.json](https://github.com/user-attachments/files/18000142/custom-dnd5e.error.json)

**Steps to reproduce**
1. Go to 'an ability that grants TEMP HP, like INSPIRING LEADER'
2. Click on 'roll "damage" to get a numer to APPLY'
3. Clic to APPLY TEMP HP

**Versions:**
- Module: [1.2.5]
- System: [dnd5e 4.1.2]
- Foundry VTT: [12.331]
- Browser: [Google Chrome 131.0.6778.86] 64 bits

**Additional context**
Any additional context.

**Comment by Larkinabout** [comment]
Fixed in 1.2.6. Thanks for the detailed issue and debug file, that made it a lot easier to identify the cause.

**Comment by Juno-N** [comment]
> Fixed in 1.2.6. Thanks for the detailed issue and debug file, that made it a lot easier to identify the cause.

Hello!! I tested version 1.2.6 and the error remains...

![Apply Temp HP](https://github.com/user-attachments/assets/209a3d5e-3d40-4865-8fc7-74b01be425f1)

![console error](https://github.com/user-attachments/assets/f0d61be7-d61d-4cae-b778-08fe476969ed)

[custom-dnd5e error.json](https://github.com/user-attachments/files/18008055/custom-dnd5e.error.json)

Check it out. 

Thanks, anyways,

**Comment by Larkinabout** [comment]
Serves me right for rushing and not actually syncing the fix.

**Comment by Juno-N** [comment]
> Try 1.2.7.

There we go!!!  All functional!!
Thanks mate! Good job!
